name: Build and Release Go Binaries

on:
  push:
    tags:
      - 'v*' 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin] 
        arch: [386,arm]  
        darwin-arch: [386,arm64]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20' 

      - name: Install dependencies
        run: go mod tidy

      - name: Build the Go binary
        run: |
           if [ "${{ matrix.os }}" != "darwin" ]; then
            GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o binggo-${{ matrix.os }}-${{ matrix.arch }} main.go
           else [ "${{ matrix.os }}" == "darwin" ]; then
            GOOS=${{ matrix.os }} GOARCH=${{ matrix.darwin-arch }} go build -o binggo-${{ matrix.os }}-${{ matrix.arch }} main.go


      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: go-build-artifacts
          path: |
            binggo-*
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a new GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            binggo-linux-arm
            binggo-linux-386
            binggo-windows-arm.exe
            binggo-windows-386.exe
            binggo-darwin-arm64
            binggo-darwin-386


        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
